const data = {
  products: [
    {
      _id: '1',
      name: 'Melatonina Pills',
      category: 'pills',
      image: '/images/p1.jpg',
      price: 50,
      countInStock: 10,
      brand: 'Sleep first',
      rating: 2.5,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Brillo soap powder',
      category: 'soap powder',
      image: '/images/p2.jpg',
      price: 103.6,
      countInStock: 20,
      brand: 'Brillo',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Kelloggs cornflakes',
      category: 'cornflakes',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Kelloggs',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Cif floorer',
      category: 'floorer',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Cif',
      rating: 2,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Pepsico potatoes',
      category: 'snacks',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Pepsico',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Nike t-shirt',
      category: 't-vestiments',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
